(* don't remove the following line, it makes the tests much easier to express *)
open BoolExpr

let test1 = (token_of_string "F" = CONST false)
let test2 = (token_of_string "(" = OP)
let test3 = (token_of_string ")" = CP)
let test4 = (token_of_string "T" = CONST true)
let test5 = (parse_bool_exp [OP; AND; OP; EQ; CONST true; CONST false; CP; OP; NOT; OP; OR; CONST true; CONST false; CP; CP; CP] = And (Eq (Const true, Const false), Not (Or (Const true, Const false))))
let test6 = (parse_bool_exp [OP;AND;CONST true; CONST true;CP] = And (Const true, Const true))
let test7 = (parse_bool_exp [OP;XOR;CONST true; CONST true;CP] = Xor (Const true, Const true))
let test8 = (parse_bool_exp [OP;EQ;OP;AND;CONST true; CONST false; CP;OP;NOT; CONST false;CP;CP] = Eq (And (Const true, Const false), Not (Const false)))
let test9 = ((eval_bool_exp (Xor(Const true, Const true)) []) = false)
let test10 = ((eval_bool_exp (Not(Xor (Const true, Const true))) []) = true)
let test11 = ((eval_bool_exp (And (Const true, Const true)) []) = true)
let test12 = ((eval_bool_exp (And (Const true, Or (Id "y", Id "x"))) []) = false)
let test13 = (subsets ["a";"b";"c"] = [[]; ["a"]; ["b"]; ["c"]; ["a"; "b"]; ["a"; "c"]; ["b"; "c"]; ["a"; "b"; "c"]])
let test14 = (subsets [[]] = [[]; [[]]])
let test15 = (subsets [-1;0;1] = [[]; [-1]; [0]; [1]; [-1; 0]; [-1; 1]; [0; 1]; [-1; 0; 1]])
let test16 = (subsets [1;0;-1] = [[]; [-1]; [0]; [1]; [0; -1]; [1; -1]; [1; 0]; [1; 0; -1]])
let test17 = (var_list (And (Id "var1", Or (Id "var1", Const false))) = ["var1"])
let test18 = (var_list (And(Id "v", Id "v")) = ["v"])
let test19 = (var_list (And(Const true, Or(Const false, Const true))) = [])
let test20 = (var_list (And(Const true, Or(Const false, Id ""))) = [""])
let test21 = (find_sat_sets (And(Const true, Or(Const false, Const true))) = [[]])
let test22 = (find_sat_sets (And(Const false, Or(Const false, Const true))) = [])
let test23 = (find_sat_sets (Or (Id "x", Or(Id "y", Id "z"))) = [["x"]; ["y"]; ["z"]; ["x"; "y"]; ["x"; "z"];
 ["y"; "z"]; ["x"; "y"; "z"]])
let test24 = (find_sat_sets (And (Id "x", And(Id "y", Id "z"))) = [["x"; "y"; "z"]])
let test25 = (find_sat_sets (And (Id "x", And(Id "y", Const false))) = [])
